### PR TITLE
Add windows

### PR DESCRIPTION
**Pull request by robertodr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
```
CMake Error:
  Running

   'D:/bld/cppe_1685090692676/_build_env/Library/bin/ninja.exe' '-C' 'D:/bld/cppe_1685090692676/work/build/cppe-core-prefix/src/cppe-core-build' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:489: multiple rules generate cppe.lib
```

**Comment by maxscheurer** [comment]
~The error maybe needs a patch in `cppe` itself? I/We could try to hook up conda-based Windows CI there?~ nvm just saw the patch files you added...

**Comment by robertodr** [comment]
the next thing I am going to try is to rewrite the CMake scripts to remove the super-build with `ExternalProject`... Google and the CMake issue board seems to suggest that this is a bug with ninja, but the `ExternalProject` stuff it's rather unnecessary for such a small project IMO.

**Comment by maxscheurer** [comment]
Ah you mean the cppe-internal super-build? I guess I did this because of Psi4, but if you succeed to remove it, I'm fine with it, great 👍

**Comment by robertodr** [comment]
It's relatively straightforward. I have some time next week to look at it

**Comment by loriab** [comment]
Hi Roberto and Max! This is a coincidence -- I was just bringing up trying to adapt this for Windows. :-)
* I second removing the superbuild. I did it for libefp/pylibefp, too, years ago, but I mean to get rid of it now. It makes sense for psi, but not for smaller projects, imo.
* I've been doing cmake overhauls in combination with Windows builds a lot this spring, and I've converged on a checklist that could be handy: https://github.com/psi4/gdma/issues/6
* The biggest thing to making Win work (if starting from a point like my c.2016 cmake) is often that the install(targets needs to be expanded to include runtime destintion (for the dll) and the projectConfig.cmake needs an overhaul to be target based. Also, `-DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` and `/EHsc` added to CXX_FLAGS. A few resources in case helpful: ambit (https://github.com/jturney/ambit/pull/58) & gdma(https://github.com/psi4/gdma/commits/v2.3.3 "add CMake buildsystem for L, M, W platforms" and "add exports to Python Module")
* I'm glad to help, do, or consult -- whatever's useful

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
Seems my changes https://github.com/maxscheurer/cppe/pull/43 have had the desired effect, _except_ for the CPython builds on macOS, where trying to `import cppe` segfaults, of all things 🤔 
```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/Users/runner/miniforge3/conda-bld/cppe_1685361527756/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
export SRC_DIR=/Users/runner/miniforge3/conda-bld/cppe_1685361527756/test_tmp
import: 'cppe'
/Users/runner/miniforge3/conda-bld/cppe_1685361527756/test_tmp/conda_test_runner.sh: line 3: 15681 Segmentation fault: 11  "/Users/runner/miniforge3/conda-bld/cppe_1685361527756/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python" -s "/Users/runner/miniforge3/conda-bld/cppe_1685361527756/test_tmp/run_test.py"
Tests failed for cppe-0.3.1-py310h41dc3d1_10.conda - moving package to /Users/runner/miniforge3/conda-bld/broken
WARNING:conda_build.build:Tests failed for cppe-0.3.1-py310h41dc3d1_10.conda - moving package to /Users/runner/miniforge3/conda-bld/broken
TESTS FAILED: cppe-0.3.1-py310h41dc3d1_10.conda
```

**Comment by robertodr** [comment]
All builds appear to work now, with the exception of those on Travis CI, which, I think, just timed out. We'll need a new release after https://github.com/maxscheurer/cppe/pull/43 is merged before this is usable though. ~I suggest I `skip: true  # [win]` again and merge. I'll remove the `skip` once the bot provides with an autoupdated recipe on new release.~

EDIT: actually, the last sentence I wrote doesn't make much sense. I'll leave this to run on my branch and we switch it when the new release is out.

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
fwiw, I think everything _except_ `Lib/site-packages` needs to be behind `Library/`. That is, `_h_env/Library/bin/cppe.dll`

```
2023-05-30T06:01:51.0854279Z -- Installing: D:/bld/cppe_1685426125781/_h_env/include/cppe/core/fmm/field_m1.hh
2023-05-30T06:01:51.0855146Z -- Installing: D:/bld/cppe_1685426125781/_h_env/include/cppe/core/fmm/field_m2.hh
2023-05-30T06:01:51.0856036Z -- Installing: D:/bld/cppe_1685426125781/_h_env/include/cppe/core/fmm/tree.hh
2023-05-30T06:01:51.0856913Z -- Installing: D:/bld/cppe_1685426125781/_h_env/include/cppe/core/fmm/utils.hh
2023-05-30T06:01:51.0858664Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/pycppe.cp38-win_amd64.pyd
2023-05-30T06:01:51.0859524Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/__init__.py
2023-05-30T06:01:51.0860428Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests
2023-05-30T06:01:51.0861323Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/cache.py
2023-05-30T06:01:51.0862150Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/dump_pyscf.py
2023-05-30T06:01:51.0863045Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/misc.py
2023-05-30T06:01:51.0864484Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/nilered.hdf5
2023-05-30T06:01:51.0865406Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/pna.hdf5
2023-05-30T06:01:51.0866329Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/potfiles
2023-05-30T06:01:51.0867266Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/potfiles/fmuls_loprop_solvated_20.txt
2023-05-30T06:01:51.0869239Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/potfiles/loprop_solvated_20.pot
2023-05-30T06:01:51.0870431Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/potfiles/make_isopol.py
2023-05-30T06:01:51.0871381Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/potfiles/pna_6w.pot
2023-05-30T06:01:51.0872256Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/potfiles/pna_6w_isopol.pot
2023-05-30T06:01:51.0873171Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/ref_fmm_errors.csv
2023-05-30T06:01:51.0874640Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/symmetry_helper.py
2023-05-30T06:01:51.0876283Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/test_fields.py
2023-05-30T06:01:51.0877376Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/test_fmm.py
2023-05-30T06:01:51.0878341Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/test_functionality.py
2023-05-30T06:01:51.0879264Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/test_gradients.py
2023-05-30T06:01:51.0880457Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/test_math.py
2023-05-30T06:01:51.0881903Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/test_options.py
2023-05-30T06:01:51.0882923Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/test_solver.py
2023-05-30T06:01:51.0883840Z -- Installing: D:/bld/cppe_1685426125781/_h_env/Lib/site-packages/cppe/tests/__init__.py
2023-05-30T06:01:51.0884637Z -- Installing: D:/bld/cppe_1685426125781/_h_env/lib/cppe.lib
2023-05-30T06:01:51.0885489Z -- Installing: D:/bld/cppe_1685426125781/_h_env/bin/cppe.dll
2023-05-30T06:01:51.0886330Z -- Installing: D:/bld/cppe_1685426125781/_h_env/include/cppe/metadata.hh
2023-05-30T06:01:51.0887123Z -- Installing: D:/bld/cppe_1685426125781/_h_env/include/cppe/libcppe.hh
2023-05-30T06:01:51.0887997Z -- Installing: D:/bld/cppe_1685426125781/_h_env/share/cmake/cppe/cppeConfig.cmake
2023-05-30T06:01:51.0888867Z -- Installing: D:/bld/cppe_1685426125781/_h_env/share/cmake/cppe/cppeConfigVersion.cmake
2023-05-30T06:01:51.0890299Z -- Installing: D:/bld/cppe_1685426125781/_h_env/share/cmake/cppe/cppeTargets.cmake
2023-05-30T06:01:51.0905880Z -- Installing: D:/bld/cppe_1685426125781/_h_env/share/cmake/cppe/cppeTargets-release.cmake
2023-05-30T06:01:51.0972479Z [0/2] Re-checking globbed directories...
```

If you want objdump back for windows, add `m2w64-binutils`  to `test/requires` https://github.com/conda-forge/psi4-feedstock/blob/main/recipe/meta.yaml#L148 .

**Comment by robertodr** [comment]
> fwiw, I think everything _except_ `Lib/site-packages` needs to be behind `Library/`. That is, `_h_env/Library/bin/cppe.dll`

I see I do that for xcfun, so might be neeeded here as well. However, Max tells me that distributing the C++ library (and headers) is not needed as all open source projects depending on CPPE use it through the Python library. I was thus going to remove compiling the library and installing it (and the headers) altogether.

> If you want objdump back for windows, add `m2w64-binutils` to `test/requires` https://github.com/conda-forge/psi4-feedstock/blob/main/recipe/meta.yaml#L148 .

Thanks for the tip! Much appreciated!

**Comment by loriab** [comment]
>> fwiw, I think everything except Lib/site-packages needs to be behind Library/. That is, _h_env/Library/bin/cppe.dll

> I see I do that for xcfun, so might be neeeded here as well. However, Max tells me that distributing the C++ library (and headers) is not needed as all open source projects depending on CPPE use it through the Python library. I was thus going to remove compiling the library and installing it (and the headers) altogether.

Ok, great, all the cleaner. And does away with the question of multiple outputs.

>> If you want objdump back for windows, add m2w64-binutils to test/requires https://github.com/conda-forge/psi4-feedstock/blob/main/recipe/meta.yaml#L148 .

> Thanks for the tip! Much appreciated!

Sure thing. Nice branch name, btw. And thanks very much for tackling the Windows migration! One more tick on the big spreadsheet https://github.com/orgs/psi4/projects/2/views/1

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by maxscheurer** [comment]
@conda-forge-admin, please rerender

**Comment by maxscheurer** [comment]
@conda-forge-admin, please restart ci

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@maxscheurer this builds on all supported platforms off of official `master` branch. I would suggest that you cut a new release and we merge this (just so it doesn't bit-rot into uselessness) even though the current version of `master` cannot build and upload wheels to PyPI.

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
