### PR TITLE
Try Windows

### PR DESCRIPTION
**Pull request by maxscheurer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by robertodr** [comment]
I am not sure how to best fix the merge conflicts, so moving work on this to #12

**Comment by robertodr** [comment]
@conda-forge-admin, please rerender

**Comment by maxscheurer** [comment]
Would be great if we could make this work @robertodr, especially since Psi4 is now on c-f, it would be cool to support cppe on Win, too (ping @loriab).

**Comment by robertodr** [comment]
giving it another try in a new branch

**Pull request closed without merging**
