### PR TITLE
try new pybind11

### PR DESCRIPTION
**Pull request by loriab**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
@conda-forge-admin, please rerender

**Comment by loriab** [comment]
Hi @maxscheurer, I think this is ready for consideration. 

Psi4 and cppe with numpy v2 is triggering some problems, and I think part of it may be that this was compiled with year-old pybind11. A rerender is probably due anyways.

The new np v1 restriction on tests was because the cppe tests were complaining about no `math` in `numpy`. There was numpy listed twice in tests, and removing one had an effect upon rerender, which seemed odd. I wanted to check with you that the double numpy wasn't something strategic.

**Review by maxscheurer — APPROVED** [review]

**Comment by maxscheurer** [comment]
Mhm... need to check what's going on with the math thing but for now should be fine!

**Pull request merged**
